{"path":"api/CsvHelper/FieldValidationException","templateID":1,"sharedPropsHashes":{"toc":"Z6psdd"},"localProps":{"className":"/FieldValidationException","data":"# FieldValidationException Class\r\n\r\nNamespace: [CsvHelper](/api/CsvHelper)\r\n\r\nRepresents a user supplied field validation failure.\r\n\r\n```cs\r\npublic class FieldValidationException : ValidationException, ISerializable\r\n```\r\n\r\nInheritance Object -> Exception -> CsvHelperException -> ValidationException -> FieldValidationException\r\n\r\n## Constructors\r\n&nbsp; | &nbsp;\r\n- | -\r\nFieldValidationException(ReadingContext, String) | Initializes a new instance of the ``CsvHelper.ValidationException`` class.\r\nFieldValidationException(ReadingContext, String, String) | Initializes a new instance of the ``CsvHelper.ValidationException`` class with a specified error message.\r\nFieldValidationException(ReadingContext, String, String, Exception) | Initializes a new instance of the ``CsvHelper.ValidationException`` class with a specified error message and a reference to the inner exception that is the cause of this exception.\r\n\r\n## Properties\r\n&nbsp; | &nbsp;\r\n- | -\r\nField | Gets the field that failed validation.\r\n"}}
